---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: glance-secrets
          volumeMounts:
            - name: glance-config
              mountPath: /app/config
              readOnly: true
            - name: glance-assets
              mountPath: /app/assets
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
        - name: glance-assets
          confiMap:
            name: glance-assets