apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: glance
  ports:
    - port: 8080          # port interne du service (et du pod)
      targetPort: 8080    # port sur lequel le pod écoute
      nodePort: 31083